"""Regenerate the topographic background: assets/img/contours.svg and
assets/js/contours.js (the same SVG inlined, so it also works from file://).

Usage: python3 tools/make_contours.py [seed]
Needs only numpy. Change the seed for a different terrain.
"""
import sys, numpy as np

seed = int(sys.argv[1]) if len(sys.argv) > 1 else 7
rng = np.random.default_rng(seed)
W, H, N = 1200, 800, 4                     # SVG size, grid spacing (px)
xs, ys = np.arange(0, W + N, N), np.arange(0, H + N, N)
X, Y = np.meshgrid(xs, ys)

# Terrain: a few broad hills plus gentle ridges.
Z = np.zeros_like(X, dtype=float)
for _ in range(9):
    cx, cy = rng.uniform(-100, W + 100), rng.uniform(-100, H + 100)
    sx, sy = rng.uniform(140, 380), rng.uniform(120, 320)
    Z += rng.uniform(0.5, 1.2) * np.exp(-(((X - cx) / sx) ** 2 + ((Y - cy) / sy) ** 2))
for _ in range(4):
    a, f, p = rng.uniform(0.04, 0.09), rng.uniform(0.004, 0.011), rng.uniform(0, 6.28)
    ang = rng.uniform(0, 3.14)
    Z += a * np.sin(f * (X * np.cos(ang) + Y * np.sin(ang)) + p)

def interp(p1, p2, v1, v2, lvl):
    t = (lvl - v1) / (v2 - v1) if v2 != v1 else 0.5
    return (p1[0] + t * (p2[0] - p1[0]), p1[1] + t * (p2[1] - p1[1]))

def march(level):
    segs = []
    rows, cols = Z.shape
    for j in range(rows - 1):
        for i in range(cols - 1):
            v = [Z[j, i], Z[j, i + 1], Z[j + 1, i + 1], Z[j + 1, i]]
            p = [(xs[i], ys[j]), (xs[i + 1], ys[j]), (xs[i + 1], ys[j + 1]), (xs[i], ys[j + 1])]
            idx = sum(1 << k for k in range(4) if v[k] > level)
            if idx in (0, 15):
                continue
            e = {}
            for k in range(4):
                a, b = k, (k + 1) % 4
                if (v[a] > level) != (v[b] > level):
                    e[k] = interp(p[a], p[b], v[a], v[b], level)
            ks = sorted(e)
            if len(ks) == 2:
                segs.append((e[ks[0]], e[ks[1]]))
            elif len(ks) == 4:
                segs.append((e[0], e[1])); segs.append((e[2], e[3]))
    return segs

def chain(segs):
    key = lambda pt: (round(pt[0], 2), round(pt[1], 2))
    adj = {}
    for s in segs:
        for a, b in (s, s[::-1]):
            adj.setdefault(key(a), []).append(b)
    used, lines = set(), []
    for s in segs:
        sid = (key(s[0]), key(s[1]))
        if sid in used:
            continue
        line = [s[0], s[1]]; used.add(sid); used.add(sid[::-1])
        for direction in (0, 1):
            while True:
                end = line[-1]
                nxt = None
                for c in adj.get(key(end), []):
                    e = (key(end), key(c))
                    if e not in used:
                        nxt = c; used.add(e); used.add(e[::-1]); break
                if nxt is None:
                    break
                line.append(nxt)
            line.reverse()
        lines.append(line)
    return lines

levels = np.linspace(Z.min() + 0.08, Z.max() - 0.02, 16)
paths = []
for n, lvl in enumerate(levels):
    for line in chain(march(lvl)):
        if len(line) < 6:
            continue
        pts = line[::2] + ([line[-1]] if len(line) % 2 == 0 else [])
        d = "M" + " L".join(f"{x:.0f} {y:.0f}" for x, y in pts)
        cls = ' class="idx"' if n % 4 == 3 else ""
        paths.append(f'<path{cls} d="{d}"/>')

svg = (f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {W} {H}" preserveAspectRatio="xMidYMid slice" '
       'fill="none" stroke="currentColor" stroke-linejoin="round" stroke-linecap="round">'
       '<style>path{stroke-width:1;opacity:.55}.idx{stroke-width:1.6;opacity:.9}</style>'
       + "".join(paths) + "</svg>")
open("assets/img/contours.svg", "w").write(svg)
import json
open("assets/js/contours.js", "w").write("/* Generated by tools/make_contours.py. Do not edit by hand. */\nwindow.CONTOURS_SVG = " + json.dumps(svg) + ";\n")
print(f"wrote {len(paths)} contour paths, {len(svg)//1024} KB")
